version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  db:
    image: postgres:16
    container_name: busbell-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: busbell
    volumes:
      - busbell_pgdata:/var/lib/postgresql/data

volumes:
  busbell_pgdata:
