version: '3.9'

services:
 redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  db:
    image: postgres:16
    container_name: busbell-db
    ports:
      - '5432:5432' # 호스트:컨테이너 포트 매핑
    environment:
      POSTGRES_USER: test # 초기 슈퍼유저
      POSTGRES_PASSWORD: test # 초기 비밀번호
      POSTGRES_DB: busbell # 자동 생성 DB
    healthcheck: # /**헬스체크: DB 준비 여부 확인*/
      test: ['CMD-SHELL', 'pg_isready -U postgres -d busbell']
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - busbell_pgdata:/var/lib/postgresql/data # /**데이터 영속화*/

volumes:
  busbell_pgdata:
